### ISSUE TITLE
Error when calling `ptb.from.file` without the package loaded with `library`

### ISSUE THREAD

**Issue by ferenci-tamas** [mkfs/r-physionet-ptb#2]
I usually try to avoid using `library` if only a few calls are performed from the package. However

    ptb <- r.physionet.ptb::ptb.from.file( "patient001.json" )

results in

    Error in fromJSON(file = path) : could not find function "fromJSON"

(The same call runs perfectly if `library(r.physionet.ptb)`  is first performed.)

**Comment by mkfs** [comment]
Haven't used R in awhile. Is using library() to load a package no longer required?

**Comment by ferenci-tamas** [comment]
Absolutely! (E.g. `MASS::truehist(rnorm(100))` runs just fine without ever loading `MASS` with `library`. Not only possible, many believes it is advisable (see https://chrisvoncsefalvay.com/defensive-programming-r/#4 for instance.)

**Comment by mkfs** [comment]
OK, I'll look into it. Got some unrelated (i.e. non-R) work on the physionet databases that I've been putting off, so might as well give this package the once-over when I do it.

**Comment by mkfs** [comment]
Didn't read that Defensive Programming page; it's written like the guy is talking to a child or a simpleton.

Looks like the calls to all library functions need to be fully-qualified, which is fine, will get to that. Package is in a  ratherpoor state - I don't know that the TuneR or Wavelet stuff was ever actually implemented, yet those are still dependencies. I wrote much better stuff for dealing with Physionet using Ruby last year; might have to see about porting it.

**Comment by mkfs** [comment]
okay fixed, also did some NAMESPACE additions.

github removed my SSH keys, however ("ERROR: We're doing an SSH key audit. Reason: legacy key automatically unverified"). 

I've wasted enough time on this nonsense. Will do a push once I have a sufficiently pressing need to make my github access work again.

**Comment by ferenci-tamas** [comment]
Thanks!
